// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import InfiniteScrollController from "./infinite_scroll_controller"
import Clipboard from '@stimulus-components/clipboard'
import Sortable from '@stimulus-components/sortable'
import NestedSortable from './nested_sortable_controller'
import Dropdown from './dropdown_controller'
import Tabs from './tabs_controller'
application.register("infinite-scroll", InfiniteScrollController)
application.register('clipboard', Clipboard)
application.register('sortable', Sortable)
application.register('nested-sortable', NestedSortable)
application.register('dropdown', Dropdown)
application.register('tabs', Tabs)
